name: Compile ESP32-S3 Firmware

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Arduino CLI
        run: |
          curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | sh
          sudo mv bin/arduino-cli /usr/local/bin/
          arduino-cli config init
          arduino-cli core update-index --additional-urls https://espressif.github.io/arduino-esp32/package_esp32_index.json
          arduino-cli core install esp32:esp32 --additional-urls https://espressif.github.io/arduino-esp32/package_esp32_index.json
          arduino-cli lib install M5Unified

      - name: Compile Sketch
        run: |
          arduino-cli compile --fqbn esp32:esp32:esp32s3 --output-dir ./build .

      - name: Upload Binary Artifact
        uses: actions/upload-artifact@v4
        with:
          name: firmware-bin
          path: ./build/*.bin
